### ISSUE TITLE
can't view react app on any other device

### ISSUE THREAD

**Issue by VanzaA** [Create-Node-App/react-extensions#12]
i tried to access from my mobile or any other device in the same network as my computer ("my-pc-IP":"port" ) and it doesn't work.

**Comment by ulises-jeremias** [comment]
@VanzaA it is working now for new projects created using the command. You can use it for production serve using `yarn serve`.

![image](https://user-images.githubusercontent.com/17727170/104039976-d803f300-51b5-11eb-925e-eb1977baed15.png)
